-- task1
SELECT * FROM CITY WHERE ID = 1661;

-- task2
SELECT CITY,STATE FROM STATION;

--task3
SELECT NAME FROM CITY WHERE POPULATION > 120000 AND COUNTRYCODE='USA';

--task-4
SELECT DISTINCT CITY FROM STATION WHERE MOD(ID,2)=0;

--task-5
SELECT COUNT(CITY)-COUNT(DISTINCT CITY) FROM STATION;